server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/rwandamove?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=RwandaMoveSecretKey2024VeryLongAndStrongKey!
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
socketio.host=0.0.0.0
socketio.port=9092
africastalking.username=sandbox
africastalking.api-key=atsk_f75c9cb34d7293e86b784cb562208cab5eff2ff5f4318d243f3ed74482cfaa3f6185dd0e
africastalking.sender-id=RwandaMove